### ISSUE TITLE
Inline code text shows white-on-white in paper dark mode

### ISSUE THREAD

**Issue by gospodinp** [jez/pandoc-markdown-css-theme#11]
It seems that the background colour for inline code text is set to a bright white, but the text colour itself is not reversed to compensate, in dark mode.

**Comment by jez** [comment]
Can you share a screenshot of what you're seeing?

It should be getting flipped, as the code to do so [is right here](https://github.com/jez/pandoc-markdown-css-theme/blob/master/docs/css/theme.css#L127-L128) and also it correctly flips it on [my personal blog](https://blog.jez.io/tenum-pro-con/):

- - - - -
<img width="772" alt="Screen Shot 2022-08-09 at 12 51 12 PM" src="https://user-images.githubusercontent.com/5544532/183748488-dbb9ca84-1fc9-4dcc-8068-149505c886f0.png">

- - - - -

<img width="769" alt="Screen Shot 2022-08-09 at 12 51 06 PM" src="https://user-images.githubusercontent.com/5544532/183748499-d0715ec3-1a0d-460f-8abd-21577eaf7663.png">

- - - - -

**Comment by gospodinp** [comment]
Hm, it does seem that you're right.  This should work.

I am using firefox 103.0.2 with dark mode on, and this is how the CSS shows in the inspector:
![image](https://user-images.githubusercontent.com/2580039/183995965-e140e22d-4a36-4f5a-bc7a-311226738c2d.png)

I think the problem is that paper.css is overriding it in a way that the solarized-paper-theme does not.  I suppose that has a simple workaround.

**Comment by jez** [comment]
Thanks for finding that. Should be fixed in master now.
