### ISSUE TITLE
Logo or Page Numbers at bottom when Print to pdf from html ? 

### ISSUE THREAD

**Issue by bugsbunny88** [jez/pandoc-markdown-css-theme#12]
Hi Jez,
very helpful project and I'm using it a lot . 
I'm not entirely sure how one would go about it but how would I be able to get page numbers at the bottom ?
currently I'm using this to get the html files and then print to pdf via the browser..
it would be nice if it was possible to do both steps at once also.

**Comment by jez** [comment]
You’ll need to add your own CSS in addition to the CSS that comes with these styles to add page numbers. (Or you can click “include headers and footers” in the browser print dialog to get the unstyled  browser default numbers.)

There are plenty of guides how to do this on the internet. Hope that helps.
