### ISSUE TITLE
sidenote numbering not incrementing

### ISSUE THREAD

**Issue by joecorsi** [jez/pandoc-markdown-css-theme#13]
sidenotes do not numerically increment. all of the sidenotes have the number '1'. it seems like there may be a conflict with the katex.min.css. if this line is commented out:

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css" />`

the sidenotes increment correctly.

**Comment by jez** [comment]
This should be fixed as of https://github.com/jez/pandoc-markdown-css-theme/commit/9bf0e9325e82c0977e6435c41f2707df7cfbb07f which has also been released as [0.12.3 in the Jekyll theme](https://rubygems.org/gems/pandoc-markdown-jekyll-theme/versions/0.12.3).

Thanks for reporting, and sorry for the disruption.
